#   docker network create fintrack-network --subnet=192.168.100.0/24

services:
  fintrack-app:
    build: .
    env_file:
      - .env
    image: fintrack-app:latest
    container_name: fintrack-app
    networks:
      - fintrack-network # Connects to the fintrack-network

  nginx:
    build:
      context: ./nginx
      args:
        NGINX_CONF: ${NGINX_CONF}
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ${SSL_CERTS_PATH}:/etc/letsencrypt:ro
    depends_on:
      - fintrack-app
    networks:
      - fintrack-network # Connects to the fintrack-network

networks:
  fintrack-network:
    external: true
    name: fintrack-network
