services:
  fintrack-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    image: fintrack-app:latest
    container_name: fintrack-app

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - fintrack-app
